tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
tap "neovim/neovim"
brew "aria2"
brew "python3"
brew "asciinema"
brew "astyle"
brew "gettext"
brew "pixman"
brew "autoconf"
brew "bash"
brew "bash-completion"
brew "bdw-gc"
brew "binutils"
brew "clang-format"
brew "cowsay"
brew "gmp"
brew "mpfr"
brew "gawk"
brew "gnu-sed"
brew "grep", args: ["with-default-names"]
brew "libtool"
brew "crosstool-ng"
brew "cscope"
brew "ctags", args: ["HEAD"]
brew "curl", args: ["with-libssh2", "with-nghttp2", "with-rtmpdump"]
brew "diffutils"
brew "lame"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "file-formula"
brew "findutils", args: ["with-default-names"]
brew "fortune"
brew "git"
brew "git-flow"
brew "gnu-getopt"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "nettle"
brew "gnupg"
brew "go"
brew "gzip"
brew "hub"
brew "irssi"
brew "libav"
brew "libcaca"
brew "libcroco"
brew "libelf"
brew "libidn"
brew "pango"
brew "librsvg"
brew "libssh2"
brew "libvterm"
brew "libyaml"
brew "llvm"
brew "lrzsz"
brew "lua"
brew "make"
brew "unibilium"
brew "neovim"
brew "node"
brew "ranger"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rtmpdump"
brew "rtv"
brew "ruby"
brew "screenfetch"
brew "sl"
brew "sphinx-doc"
brew "thefuck"
brew "tig"
brew "tmux", args: ["HEAD", "with-utf8proc"]
brew "toilet"
brew "tree"
brew "unrar"
brew "unzip"
brew "vim", args: ["HEAD", "with-override-system-vi", "with-python3"]
brew "w3m"
brew "wget"
brew "youtube-dl", args: ["HEAD"]
brew "zsh"
brew "zsh-completions"
cask "adium"
cask "emacs"
cask "java"
cask "keycastr"
cask "transmission"
